# Generated by Django 2.2.4 on 2019-09-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todofeed',
        ),
    ]
